 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/rreplies", type: :request do
  # Rreply. As you add validations to Rreply, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Rreply.create! valid_attributes
      get rreplies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      rreply = Rreply.create! valid_attributes
      get rreply_url(rreply)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_rreply_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      rreply = Rreply.create! valid_attributes
      get edit_rreply_url(rreply)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Rreply" do
        expect {
          post rreplies_url, params: { rreply: valid_attributes }
        }.to change(Rreply, :count).by(1)
      end

      it "redirects to the created rreply" do
        post rreplies_url, params: { rreply: valid_attributes }
        expect(response).to redirect_to(rreply_url(Rreply.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Rreply" do
        expect {
          post rreplies_url, params: { rreply: invalid_attributes }
        }.to change(Rreply, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post rreplies_url, params: { rreply: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rreply" do
        rreply = Rreply.create! valid_attributes
        patch rreply_url(rreply), params: { rreply: new_attributes }
        rreply.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the rreply" do
        rreply = Rreply.create! valid_attributes
        patch rreply_url(rreply), params: { rreply: new_attributes }
        rreply.reload
        expect(response).to redirect_to(rreply_url(rreply))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        rreply = Rreply.create! valid_attributes
        patch rreply_url(rreply), params: { rreply: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested rreply" do
      rreply = Rreply.create! valid_attributes
      expect {
        delete rreply_url(rreply)
      }.to change(Rreply, :count).by(-1)
    end

    it "redirects to the rreplies list" do
      rreply = Rreply.create! valid_attributes
      delete rreply_url(rreply)
      expect(response).to redirect_to(rreplies_url)
    end
  end
end
