 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/rreply_favorites", type: :request do
  # RreplyFavorite. As you add validations to RreplyFavorite, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RreplyFavorite.create! valid_attributes
      get rreply_favorites_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      rreply_favorite = RreplyFavorite.create! valid_attributes
      get rreply_favorite_url(rreply_favorite)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_rreply_favorite_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      rreply_favorite = RreplyFavorite.create! valid_attributes
      get edit_rreply_favorite_url(rreply_favorite)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RreplyFavorite" do
        expect {
          post rreply_favorites_url, params: { rreply_favorite: valid_attributes }
        }.to change(RreplyFavorite, :count).by(1)
      end

      it "redirects to the created rreply_favorite" do
        post rreply_favorites_url, params: { rreply_favorite: valid_attributes }
        expect(response).to redirect_to(rreply_favorite_url(RreplyFavorite.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RreplyFavorite" do
        expect {
          post rreply_favorites_url, params: { rreply_favorite: invalid_attributes }
        }.to change(RreplyFavorite, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post rreply_favorites_url, params: { rreply_favorite: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rreply_favorite" do
        rreply_favorite = RreplyFavorite.create! valid_attributes
        patch rreply_favorite_url(rreply_favorite), params: { rreply_favorite: new_attributes }
        rreply_favorite.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the rreply_favorite" do
        rreply_favorite = RreplyFavorite.create! valid_attributes
        patch rreply_favorite_url(rreply_favorite), params: { rreply_favorite: new_attributes }
        rreply_favorite.reload
        expect(response).to redirect_to(rreply_favorite_url(rreply_favorite))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        rreply_favorite = RreplyFavorite.create! valid_attributes
        patch rreply_favorite_url(rreply_favorite), params: { rreply_favorite: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested rreply_favorite" do
      rreply_favorite = RreplyFavorite.create! valid_attributes
      expect {
        delete rreply_favorite_url(rreply_favorite)
      }.to change(RreplyFavorite, :count).by(-1)
    end

    it "redirects to the rreply_favorites list" do
      rreply_favorite = RreplyFavorite.create! valid_attributes
      delete rreply_favorite_url(rreply_favorite)
      expect(response).to redirect_to(rreply_favorites_url)
    end
  end
end
